# Generated by Django 4.2.17 on 2025-03-11 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('type', models.CharField(choices=[('router', 'Router'), ('phone', 'Phone'), ('pc', 'PC'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='schoolApp.school')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
