# Generated by Django 4.2.17 on 2025-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.AddField(
            model_name='device',
            name='check_ports',
            field=models.CharField(blank=True, help_text="Comma-separated ports to check (e.g., '80,443,22')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_connectivity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='use_ping_fallback',
            field=models.BooleanField(default=True),
        ),
    ]
