# Generated by Django 4.2.17 on 2025-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
        ('deviceApp', '0002_remove_device_status_device_check_ports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connectivity_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_check_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'school', 'ip_address')},
        ),
    ]
