# Generated by Django 4.2.17 on 2025-03-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0004_device_is_local_network_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='deviceApp_d_mac_add_fb4302_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='deviceApp_d_school__ecad9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='deviceApp_d_ip_addr_157d6d_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_local_network',
        ),
    ]
