# Generated by Django 4.2.17 on 2025-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0005_remove_device_deviceapp_d_mac_add_fb4302_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connectivity_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ping_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='device',
            name='retry_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='device',
            name='timeout',
            field=models.IntegerField(default=5),
        ),
    ]
