# Generated by Django 4.2.17 on 2025-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0006_device_connectivity_details_device_ping_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('router', 'Router'), ('access_point', 'Access Point')], max_length=50),
        ),
    ]
