# Generated by Django 4.2.17 on 2025-03-15 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deviceApp', '0007_alter_device_type'),
        ('routerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Router',
        ),
    ]
