# Generated by Django 4.2.17 on 2025-03-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerApp', '0002_rename_device_router'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='type',
        ),
    ]
