# Generated by Django 4.2.17 on 2025-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerApp', '0003_remove_router_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='type',
            field=models.CharField(default='router', max_length=100),
        ),
    ]
